spring:
  application:
    name: spring-cloud-config-poc
  profiles:
    active: local,development,production
  cloud:
    config:
      server:
        git:
          uri: https://github.com/higodev/spring-cloud-config-poc
          search-paths: properties/
server:
  port: 8888
management:
  security:
    enabled: false
